server:
  port: 18080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # jws-algorithms: RS512                         # Trusted Alg.
          issuer-uri: http://localhost:20080/realms/temp  #
          jwk-set-uri: http://localhost:20080/realms/temp/protocol/openid-connect/certs
          # public-key-location: hfds://my-key.pub        # JWK Set 공개 키 파일로 지정
#         # audiences:                                    # aud 검증 시 대조 값

logging.level:
  org.springframework.security: DEBUG
